### ISSUE TITLE
Queue only accepts people until 30 players

### ISSUE THREAD

**Issue by CruelAlpha** [LuaDeldu/rocademption#2]
Hello,
This is a great queing script, far better than most released.
I was wondering if there was a way to remove the cap on 30 players, for example;
The server is 32 slots but the queue constantly keeps people in the queue since it's reached 30 players, it doesn't fill the 2 other slots remaining. 
I have removed hard cap etc but still doesn't seem to be working.

**Comment by CruelAlpha** [comment]
Never mind fixed by checking the max players.

**Comment by lucasvperini** [comment]
Hey!

Here? 
![image](https://user-images.githubusercontent.com/47780889/57500177-ccfa1080-72b8-11e9-9c0a-e31abf28716c.png)
I've put 32 slots on it, still capped at 30 players...
Any ideas?

Thanks!
